[explain]
prompt = """\
  Explain the following code snippet, but not line by line. \
  Give a general overview of the code: why it might have been implemented this way, its purpose, its quirks, and possible improvements, if any.\
"""

[review]
prompt = """\
  Review the following code snippet. \
  Make sure it follows established best practices, is clean, efficient and maintainable. \
  Pay close attention to common mistakes like syntax errors, logic errors, security vulnerabilities, \
  performance and scalability issues, or anything that seems questionable. \
  For each mistake found, explain what is wrong and how to correct or improve it. \
  Give your answer as one bullet point per mistake found.\
"""

[r1]
[r1.options]
model = "deepseek-reasoner"
temperature = 0.6
requestTimeout = 20
initialPrompt = ""

[fw-v3]
[fw-v3.options]
model = "accounts/fireworks/models/deepseek-v3"
endpointUrl = "https://api.fireworks.ai/inference/v1/chat/completions"

[fw-r1]
[fw-r1.options]
model = "accounts/fireworks/models/deepseek-r1"
endpointUrl = "https://api.fireworks.ai/inference/v1/chat/completions"
temperature = 0.6
requestTimeout = 20
initialPrompt = ""
