let g:airline_theme='base16_monokai'
"let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ''
let g:airline#extensions#tabline#right_sep = ''
let g:airline_theme='base16_monokai'
let g:airline_left_sep=''
let g:airline_left_alt_sep=""
let g:airline_right_sep=''
let g:airline_right_alt_sep=""
